### ISSUE TITLE
CEF control ignoring key inputs while upgrading the example projects to Avalonia 11

### ISSUE THREAD

**Issue by bogatkov** [Haltroy/CefNet.Avalonia.Examples#1]
Issue explained here: bkempinski/CefNet.Avalonia/issues/1.

Reproduced it on Ubuntu 18.04 also.

**Comment by Haltroy** [comment]
The original CefNet repository is deleted (well it wasn't actively developed for more than 2 years anyways) and these examples were based on that version of CefNet and I don't have any knowledge about the Avalonia 11 port for now. Will try my best to fix this issue if this is related to the example projects but for now it looks like upstream issue. 

Also, since the CefNet project is dead, I recommend waiting [CefGlue](https://github.com/OutSystems/CefGlue) to finally have Avalonia 11 support since there's more active development there and in the future it might also get a Linux port (which is what I'm waiting for).

**Comment by bogatkov** [comment]
According to https://github.com/bkempinski/CefNet.Avalonia/issues/1#issuecomment-1766024754, the key input works (except for the IME mode) if you add:

```c#
webview.Focusable = true;
```

**Comment by Haltroy** [comment]
If that fixes it then I'm committing this change. Also since the original CefNet repository is dead now, I'm going to make another example repository for the Avalonia 11 port and redirect people to there and archive this one until something happens.
