### ISSUE TITLE
Main method fired multiple times

### ISSUE THREAD

**Issue by ebesnard** [Haltroy/CefNet.Avalonia.Examples#3]
Hi,

Your examples work fine so it's not really an issue but I noticed the Main method was fired multiple times in the CefNet.AvaloniaMVVM.Example.

Why this?

**Comment by Haltroy** [comment]
CEF when run on multi-threaded mode (which is default), spawns multiple processes for multiple tasks in order to show the content of the web page. This approach is visible in Chromium and Chrome and any other Chromium-based web browser as well.
In other CEF wrappers (like CefSharp and CefGlue) have a special C# project (or in executable form) in them called "Subprocess" which handles the other process calls needed for CEF to work (ex. GPU process, network process etc.)
CefNet does not have this feature so it relies on the main application to do the multi-process handling.

Closing the issue since this is sadly the intentional feature of CefNet (which no longer exists) but feel free to ask any questions.

**Comment by ebesnard** [comment]
Thanks a lot for your explanations. I am interested in CefNet because it supports Avalonia and works under Linux. Not sure CefSharp and CefGlue are compatible with Avalonia and/or Linux.

**Comment by Haltroy** [comment]
CefSharp at its core is written in Visual C++ which is not cross-platform like C++ itself and the CefSharp dev team did refuse to make it work for Avalonia. However, me and other people are working on trying to make CefGlue work on Linux ([this PR request](https://github.com/OutSystems/CefGlue/pull/121) and [also this PR](https://github.com/OutSystems/CefGlue/pull/88) and [this repository](https://github.com/haltroy/CefGlue)). Hopefully in the future we can have a C# wrapper for CEF that works on Linux.
